### ISSUE TITLE
Add installation note

### ISSUE THREAD

**Issue by Frotty** [Dominaezzz/kotlin-sqlite#2]
I can't seem to get this working. The bintray dependency doesn't work for me, I always get this error.
```
Could not resolve com.github.dominaezzz:kotlin-sqlite-core:0.2.5-dev-2.
```

Even with
```
maven {
            url "https://dl.bintray.com/dominaezzz/kotlin-native"
        }
```

I tried building via jitpack but it fails https://jitpack.io/com/github/Dominaezzz/kotlin-sqlite/0.2.5-dev-2/build.log

**Comment by Dominaezzz** [comment]
Which version of Kotlin and Gradle are you using? Which targets are you targeting?

**Comment by Frotty** [comment]
> Which version of Kotlin and Gradle are you using?

`ext.kotlinVersion = '1.3.61'`

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-bin.zip`

> Which targets are you targeting?

Desktop 1.8 or which targets do you mean?

**Comment by Dominaezzz** [comment]
`1.8`? You're targeting jvm? This library doesn't support the JVM yet.

**Comment by Frotty** [comment]
yeah it's a mixed java/kotlin project. Okay thanks for the response.
